# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Jewwllary_App"
client_id = "fc7437778c47a6f7d6dc8f1780e23757"
application_url = "https://panels-ups-fantasy-navigator.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://panels-ups-fantasy-navigator.trycloudflare.com/auth/callback",
  "https://panels-ups-fantasy-navigator.trycloudflare.com/auth/shopify/callback",
  "https://panels-ups-fantasy-navigator.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "storeapp-dev.myshopify.com"
